name: Test and Build

on: [push] # This workflow will run on each push to the repository

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
        node-version: 16.x
     - run: python hello.py

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test # This job depends on the 'test' job
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
           node-version: 16.x
     - uses: actions/upload-artifact@v2
       with:
        name: hello
        path: .
